clear;
close all;

figure('Name','Summing and differential amplifiers');

% bacground
hAxes = axes('Units', 'normalized', 'Position', [0 0 1 1]);
uistack(hAxes,'Bottom');
img  = imread('background.jpg');
image(img, 'Parent', hAxes);
set(hAxes,'HandleVisibility', 'off', 'Visible', 'off')

h = uimenu('Label', 'Amplifiers');

h1 = uimenu(h,'Label','Non-inverting summing amplifier');
uimenu(h1,'Label', 'Sinusoidal input', 'Callback', 'summing_noninverted_sin(A1, f1, A2, f2, R1, R2, R3, R4)');
uimenu(h1,'Label', 'Triangular input', 'Callback', 'summing_noninverted_triangle(A1, f1, A2, f2, R1, R2, R3, R4)');

h2 = uimenu(h,'Label','Inverting summing amplifier');
uimenu(h2,'Label', 'Sinusoidal input', 'Callback', 'summing_inverted_sin(A1, f1, A2, f2, R, R1, R2)');
uimenu(h2,'Label', 'Triangular input', 'Callback', 'summing_inverted_triangle(A1, f1, A2, f2, R, R1, R2)');

h3 = uimenu(h,'Label','Differential amplifier');
uimenu(h3,'Label', 'Sinusoidal input', 'Callback', 'differential_sin(A1, f1, A2, f2, R1, R2, R3, R4)');
uimenu(h3,'Label', 'Triangular input', 'Callback', 'differential_triangle(A1, f1, A2, f2, R1, R2, R3, R4)');

A1 = 1; % amplitude 1
f1 = 100; % frequency 1
A2 = 2; % amplitude 2
f2 = 100; % frequency 2
R = 1e3; % resistor
R1 = 1e3; % resistor 1
R2 = 1e3; % resistor 2
R3 = 1e3; % resistor 3
R4 = 1e3; % resistor 4

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.05 0.50 0.30 0.1], ...
'String', 'Non-inverting summing amplifier', ...
'Callback', 'summing_noninverted_sin(A1, f1, A2, f2, R1, R2, R3, R4)');

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.05 0.30 0.30 0.1], ...
'String', 'Inverting summing amplifier', ...
'Callback', 'summing_inverted_sin(A1, f1, A2, f2, R, R1, R2)');

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.05 0.10 0.30 0.1], ...
'String', 'Differential amplifier', ...
'Callback', 'differential_sin(A1, f1, A2, f2, R1, R2, R3, R4)');

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.35 0.70 0.30 0.1], ...
'String', 'Front page', ...
'Callback', 'front_page');

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.65 0.50 0.30 0.1], ...
'String', 'Bibliography', ...
'Callback', 'bibliography');

uicontrol('Style', 'pushbutton', ...
'Units', 'normalized', ...
'Position', [0.65 0.30 0.30 0.1], ...
'String', 'Theoretical documentation', ...
'Callback', 'theory');

% close button
uicontrol('Style', 'pushbutton',...
'Units', 'normalized',...
'Position', [0.65 0.10 0.30 0.1],...
'String', 'Close',...
'Callback', 'close');